export type JourneyPhase = "pregnancy" | "infancy";

export interface Verse {
  text: string;
  ref: string;
}

export interface Stage {
  stage: string;
  phase: JourneyPhase;
  index: number;
  title: string;
  body: string;
  verse: Verse;
  reflection: string;
  action: string;
  partnerFocus: string;
  prayerPoint: string;
}

export const STAGES: Stage[] = [
  {
    stage: "week-1",
    phase: "pregnancy",
    index: 0,
    title: "Week 1 — Before the beginning",
    body: "This first week is counted before conception, measured from the close of your last cycle. Nothing is visible yet, and much is unknown to you. Still, the whole story is already open before the One who ordains it.",
    verse: {
      text: "Your eyes saw my unformed substance; in your book were written, every one of them, the days that were formed for me, when as yet there was none of them.",
      ref: "Psalm 139:16",
    },
    reflection: "You are at the very start of something you cannot yet see or control. That is a good place to learn to trust the God who already sees the end.",
    action: "Begin a simple journal and write down the date you started this journey.",
    partnerFocus: "Sit with her and mark this beginning together; tell her you are in this from the first day, not just the visible ones. Pray that God would settle both your hearts under his timing.",
    prayerPoint: "Ask the Lord to prepare your hearts and your home for whatever he has written in his book, and to give you both a quiet trust in his hidden work.",
  },
  {
    stage: "week-2",
    phase: "pregnancy",
    index: 1,
    title: "Week 2 — Quiet preparation",
    body: "Your body is quietly making ready, and conception may be drawing near. Nothing feels different, and yet unseen preparations are underway. What looks like ordinary days are the setting for extraordinary grace.",
    verse: {
      text: "In the beginning, God created the heavens and the earth.",
      ref: "Genesis 1:1",
    },
    reflection: "The God who spoke worlds into being from nothing is not troubled by small beginnings. He works in the unseen before he shows the seen.",
    action: "Take a slow walk together this week and talk plainly about your hopes.",
    partnerFocus: "Ask her how she is feeling in body and spirit, and simply listen without fixing. Pray with her before you sleep, even briefly.",
    prayerPoint: "Praise God as the Maker of all things, and ask him to be the Maker and Keeper of this new life he may be beginning.",
  },
  {
    stage: "week-3",
    phase: "pregnancy",
    index: 2,
    title: "Week 3 — A single spark of life",
    body: "Around now, two cells become one, and a whole person begins from a single spark you cannot see. Everything that makes this child uniquely themselves is already set. No microscope caught the moment, but heaven did.",
    verse: {
      text: "For you formed my inward parts; you knitted me together in my mother's womb.",
      ref: "Psalm 139:13",
    },
    reflection: "From the first cell, this is a person known and loved by God, not a project you must complete. Your part is to steward what he has begun.",
    action: "Thank God out loud today for a life so small it is still hidden from you.",
    partnerFocus: "Guard your words about the future from pressure and expectation; speak of the child as a gift, not a demand. Pray that God would knit this life together in secret.",
    prayerPoint: "Ask the Lord who forms the inward parts to protect this tiny life and to hold it in his own hands where you cannot reach.",
  },
  {
    stage: "week-4",
    phase: "pregnancy",
    index: 3,
    title: "Week 4 — Smaller than a seed",
    body: "The tiny one settles in and takes root, smaller than a poppy seed. The first structures that will become a heart and spine begin to gather. So much is happening in a space too small to see.",
    verse: {
      text: "Before I formed you in the womb I knew you, and before you were born I consecrated you.",
      ref: "Jeremiah 1:5",
    },
    reflection: "Before you knew this child existed, God already knew them by name. You are not the author of this life, only a witness to it.",
    action: "Choose one quiet moment each day this week to pray for the baby.",
    partnerFocus: "Begin praying by name for the child even before you have a name, asking God to consecrate this little life to himself. Remind her that God knew this child before either of you did.",
    prayerPoint: "Ask God, who knew this child before the womb, to set them apart for his own purposes from the very start.",
  },
  {
    stage: "week-5",
    phase: "pregnancy",
    index: 4,
    title: "Week 5 — A first flutter of a heart",
    body: "A minute heart begins its first flutters this week, and the earliest lines of the brain and spine appear. It is all still no bigger than a grain of rice. And already there is a rhythm where before there was none.",
    verse: {
      text: "You clothed me with skin and flesh, and knit me together with bones and sinews.",
      ref: "Job 10:11",
    },
    reflection: "A heartbeat you cannot yet hear is being kept by the God who never sleeps. Every beat is measured out by him.",
    action: "Rest a hand over your midsection and pray a blessing over the small heart within.",
    partnerFocus: "Take on a chore or two so she can rest more this week without asking. Pray that God would keep the little heart beating steady and strong.",
    prayerPoint: "Thank the Lord for the gift of a beating heart, and ask him to sustain every beat by his power alone.",
  },
  {
    stage: "week-6",
    phase: "pregnancy",
    index: 5,
    title: "Week 6 — Tiny buds appear",
    body: "Small buds appear where arms and legs will grow, and the face begins its earliest shaping. The heart is beating more steadily now. A person is unfolding in miniature.",
    verse: {
      text: "I praise you, for I am fearfully and wonderfully made. Wonderful are your works; my soul knows it very well.",
      ref: "Psalm 139:14",
    },
    reflection: "What is forming in you is fearful and wonderful, worthy of praise long before it is finished. Wonder is the right response, not worry.",
    action: "Say aloud one thing about God's craftsmanship that leaves you in awe today.",
    partnerFocus: "Notice if she is weary or unwell and quietly lighten her load; wonder aloud with her at what God is making. Pray in thanks for his handiwork.",
    prayerPoint: "Praise God for his wonderful works, and ask that both of you would meet this season with awe rather than anxiety.",
  },
  {
    stage: "week-7",
    phase: "pregnancy",
    index: 6,
    title: "Week 7 — The brain grows quickly",
    body: "The brain is growing at a remarkable pace this week, and the face gathers its first features. Little arm and leg buds are lengthening. Each day brings changes too small to feel but real all the same.",
    verse: {
      text: "My frame was not hidden from you, when I was being made in secret, intricately woven in the depths of the earth.",
      ref: "Psalm 139:15",
    },
    reflection: "Nothing about this hidden work is hidden from God. He watches every intricate thread being woven.",
    action: "Write a short note to your baby telling them they are already loved.",
    partnerFocus: "Ask her what would help her most this week and then do it without being reminded again. Pray that God would watch over the secret weaving of this child.",
    prayerPoint: "Ask the Lord to guard the mind and body being formed in secret, knowing that nothing is hidden from his sight.",
  },
  {
    stage: "week-8",
    phase: "pregnancy",
    index: 7,
    title: "Week 8 — Fingers and toes",
    body: "Tiny fingers and toes are taking shape, and the major organs have all begun their work. The little one is now about the size of a raspberry. Movement has started, though far too gentle to feel.",
    verse: {
      text: "As you do not know the way the spirit comes to the bones in the womb of a woman with child, so you do not know the work of God who makes everything.",
      ref: "Ecclesiastes 11:5",
    },
    reflection: "You do not have to understand the work of God to trust the God who is at work. Mystery is not the same as chaos.",
    action: "Make peace with one thing you cannot control by naming it in prayer.",
    partnerFocus: "When she voices a worry, resist explaining it away; carry it to God with her instead. Pray that you would both rest in what you cannot understand.",
    prayerPoint: "Confess that you do not know all the ways of God, and ask him for peace in the mysteries of this unfolding life.",
  },
  {
    stage: "week-9",
    phase: "pregnancy",
    index: 8,
    title: "Week 9 — The first small movements",
    body: "The baby begins to make small, unfelt movements this week, stretching and shifting in a space no larger than a grape. Essential features are all present now, waiting to mature. Life is quietly on the move.",
    verse: {
      text: "Did not he who made me in the womb make him? And did not one fashion us in the womb?",
      ref: "Job 31:15",
    },
    reflection: "The same God who made you is making this child, with equal care and equal love. You share one Maker.",
    action: "Look back with thanks at how God formed you before you form expectations of your child.",
    partnerFocus: "Speak tenderly about the child's full humanity and worth, whatever their future holds. Pray thanks for the God who fashioned you both.",
    prayerPoint: "Thank the one Maker who fashioned you in the womb and is now fashioning your child with the same skillful care.",
  },
  {
    stage: "week-10",
    phase: "pregnancy",
    index: 9,
    title: "Week 10 — Vital organs at work",
    body: "The vital organs are now formed and beginning to function together, and tiny nails start to appear on fingers and toes. The little one is roughly the size of a strawberry. What was fragile is steadily strengthening.",
    verse: {
      text: "Yet you are he who took me from the womb; you made me trust you at my mother's breasts.",
      ref: "Psalm 22:9",
    },
    reflection: "God is already the keeper of this child, teaching trust before the child could ever speak. His care begins in the womb and never ends.",
    action: "Name one fear to your husband or a trusted friend instead of carrying it alone.",
    partnerFocus: "Make yourself a safe place for her fears by receiving them without judgment. Pray that this child would learn, in time, to trust the Lord.",
    prayerPoint: "Ask God, who keeps this child in the womb, to be their refuge and trust all the days of their life.",
  },
  {
    stage: "week-11",
    phase: "pregnancy",
    index: 10,
    title: "Week 11 — Practicing to move",
    body: "Nearly all the body's structures are present now, and the baby practices moving arms and legs in the fluid. The head is still large compared to the body, cradling that fast-growing brain. Practice is quietly underway for a life of motion.",
    verse: {
      text: "Behold, children are a heritage from the LORD, the fruit of the womb a reward.",
      ref: "Psalm 127:3",
    },
    reflection: "This child is a gift entrusted to you, not a possession earned by you. A heritage is received, then stewarded.",
    action: "Thank God for entrusting you with a life, and ask to be a faithful steward of it.",
    partnerFocus: "Talk together about the kind of home you want to build for this child, rooted in Scripture. Pray, receiving the child as a gift rather than a right.",
    prayerPoint: "Thank the Lord for the heritage of children, and ask him to make you faithful stewards of the gift he is giving.",
  },
  {
    stage: "week-12",
    phase: "pregnancy",
    index: 11,
    title: "Week 12 — A face takes shape",
    body: "The features of a distinct little face are coming together this week as the first trimester draws to a close. Reflexes are developing, and the baby may curl fingers or open and close their mouth. A recognizable person is emerging.",
    verse: {
      text: "When Elizabeth heard the greeting of Mary, the baby leaped in her womb.",
      ref: "Luke 1:41",
    },
    reflection: "Scripture treats the child in the womb as fully a person, capable of response and worthy of welcome. You are not waiting for a person to arrive; one is already here.",
    action: "Welcome your child aloud by speaking a few kind words toward your belly.",
    partnerFocus: "Begin talking to the baby so your voice becomes familiar, and encourage her that this first stretch is nearly through. Pray in gratitude as one season gives way to the next.",
    prayerPoint: "Thank God that this child is already a person before him, and ask him to knit your affection to this little one.",
  },
  {
    stage: "week-13",
    phase: "pregnancy",
    index: 12,
    title: "Week 13 — Fingerprints form",
    body: "Unique fingerprints are beginning to form on those tiny fingertips, patterns no other person will ever share. The vocal cords are developing too. Everything about this child is being marked as one of a kind.",
    verse: {
      text: "Upon you I have leaned from before my birth; you are he who took me from my mother's womb.",
      ref: "Psalm 71:6",
    },
    reflection: "God writes a signature on every life that has never been written before. This child will be like no one else because he made them so.",
    action: "Pray that your child would lean on the Lord from their earliest days.",
    partnerFocus: "Delight aloud in the child's uniqueness rather than comparing to any other. Pray that your child would depend on God from before birth.",
    prayerPoint: "Praise God for making this child utterly unrepeatable, and ask that they would lean on him from the very beginning.",
  },
  {
    stage: "week-14",
    phase: "pregnancy",
    index: 13,
    title: "Week 14 — First expressions",
    body: "The baby may begin to make small facial expressions now, squinting or frowning as the muscles practice. Some little ones start to bring a thumb toward the mouth. The face is learning to move before anyone will see it.",
    verse: {
      text: "Thus says the LORD who made you, who formed you from the womb and will help you.",
      ref: "Isaiah 44:2",
    },
    reflection: "The God who is forming this child has also promised to help you carry them. He does not make and then abandon.",
    action: "Ask God specifically for the help you need in this season, and expect him to give it.",
    partnerFocus: "Ask her plainly what help she needs and give it before she has to ask twice. Pray that God would strengthen you both as the pregnancy carries on.",
    prayerPoint: "Ask the Lord who forms this child from the womb to help you both faithfully as the weeks unfold.",
  },
  {
    stage: "week-15",
    phase: "pregnancy",
    index: 14,
    title: "Week 15 — Bones begin to harden",
    body: "The soft framework of the skeleton is slowly hardening into bone, and the baby may begin to sense light beyond the womb. Little movements are becoming stronger. What was pliable is being given quiet strength.",
    verse: {
      text: "The LORD is my shepherd; I shall not want.",
      ref: "Psalm 23:1",
    },
    reflection: "The Shepherd who tends this child will tend you too, providing what each of you truly needs. To be shepherded is to lack no good thing.",
    action: "Write down three ways God has provided for you this month.",
    partnerFocus: "Look for a need she has not mentioned and quietly meet it, shepherding her as Christ shepherds you both. Pray that the Lord would provide for your growing family.",
    prayerPoint: "Thank the Good Shepherd for his care, and ask him to provide all that your family needs in this season.",
  },
  {
    stage: "week-16",
    phase: "pregnancy",
    index: 15,
    title: "Week 16 — Ears settle into place",
    body: "The ears are moving into their final position, and the baby may begin to catch muffled sounds from the world outside. Your voice is among the first sounds they will ever know. The child is starting to listen.",
    verse: {
      text: "Come to me, all who labor and are heavy laden, and I will give you rest.",
      ref: "Matthew 11:28",
    },
    reflection: "The One your child will one day hear about is inviting you to rest in him now. Carry your load to him rather than under it.",
    action: "Read or sing a short passage of Scripture aloud so your baby hears it.",
    partnerFocus: "Read Scripture or sing over the baby together in the evenings so both parents' voices become familiar. Pray for rest for a body that is working hard.",
    prayerPoint: "Ask Jesus to give rest to weary hearts, and pray that this child would one day hear and answer his call to come.",
  },
  {
    stage: "week-17",
    phase: "pregnancy",
    index: 16,
    title: "Week 17 — Growing stronger",
    body: "A soft layer of fat is beginning to form, helping the baby regulate warmth in time. The umbilical cord grows stronger to carry all that the little one needs. Steady provision flows to a growing child.",
    verse: {
      text: "Casting all your anxieties on him, because he cares for you.",
      ref: "1 Peter 5:7",
    },
    reflection: "You were not meant to carry your anxieties and your child at the same time. Hand one of them over.",
    action: "Name one anxiety in prayer and deliberately leave it with the Lord.",
    partnerFocus: "Invite her to name her worries aloud, then pray each one back to God together. Remind her that his care for you both is settled and sure.",
    prayerPoint: "Cast your anxieties on the Lord, trusting that his care for your family is deeper than your fears.",
  },
  {
    stage: "week-18",
    phase: "pregnancy",
    index: 17,
    title: "Week 18 — The first felt movements",
    body: "Somewhere around now you may feel the earliest flutters, faint as a butterfly or a bubble. These first felt movements are often called quickening. What was only believed can now be gently felt.",
    verse: {
      text: "The LORD your God is in your midst, a mighty one who will save; he will rejoice over you with gladness; he will quiet you by his love; he will exult over you with loud singing.",
      ref: "Zephaniah 3:17",
    },
    reflection: "As you rejoice over the child within you, remember that God rejoices over you with singing. You are cherished by the One you are learning to cherish this little one for.",
    action: "Pause and give thanks the first time you notice the baby move.",
    partnerFocus: "Share her joy at these first movements and treasure the moment you first feel the baby yourself. Pray, remembering that God rejoices over your family with singing.",
    prayerPoint: "Praise God who sings over his people, and thank him for the first stirrings of life you can feel.",
  },
  {
    stage: "week-19",
    phase: "pregnancy",
    index: 18,
    title: "Week 19 — A protective covering",
    body: "A soft, waxy coating now covers the baby's delicate skin, guarding it in the watery world of the womb. The senses are steadily developing. Even here, the little one is being protected in ways you never arranged.",
    verse: {
      text: "He will cover you with his pinions, and under his wings you will find refuge; his faithfulness is a shield and buckler.",
      ref: "Psalm 91:4",
    },
    reflection: "The God who covers this child in the womb covers you under his wings. Refuge is not something you build; it is someone you run to.",
    action: "Find a quiet place today and simply rest under God's protection for a few minutes.",
    partnerFocus: "Be a covering for her, guarding her rest and shielding her from needless stress. Pray that God would be the true refuge of your whole household.",
    prayerPoint: "Thank God for his sheltering care, and ask him to be the refuge of your family in every season to come.",
  },
  {
    stage: "week-20",
    phase: "pregnancy",
    index: 19,
    title: "Week 20 — Halfway there",
    body: "You have reached the midpoint of the journey. The baby is swallowing small amounts of fluid, fine hair is growing, and movements are becoming more regular. Half the waiting is behind you now.",
    verse: {
      text: "The steadfast love of the LORD never ceases; his mercies never come to an end; they are new every morning; great is your faithfulness.",
      ref: "Lamentations 3:22-23",
    },
    reflection: "Halfway through, you have already received mercy upon mercy, new every single morning. Look back and count the faithfulness that carried you here.",
    action: "Mark the halfway point by thanking God for his mercies over these twenty weeks.",
    partnerFocus: "Celebrate this milestone together in some small, deliberate way. Pray, thanking God for his fresh mercies through the first half of this journey.",
    prayerPoint: "Praise the Lord for mercies new every morning, and ask for grace to trust his faithfulness through the second half.",
  },
  {
    stage: "week-21",
    phase: "pregnancy",
    index: 20,
    title: "Week 21 — Growing by the day",
    body: "The baby is growing steadily now and beginning to develop the sense of taste as they swallow. Movements are stronger and more frequent, a language all their own. Day by day, the little one fills out and grows.",
    verse: {
      text: "The LORD will fulfill his purpose for me; your steadfast love, O LORD, endures forever. Do not forsake the work of your hands.",
      ref: "Psalm 138:8",
    },
    reflection: "The God who began this good work will bring it to completion in his time. He does not abandon what his own hands have started.",
    action: "Pray that God would fulfill his good purposes in your child's whole life.",
    partnerFocus: "Encourage her when the growing feels slow, reminding her that God finishes what he starts. Pray for God's purposes to be fulfilled in this child.",
    prayerPoint: "Ask the Lord to fulfill his purpose for your child, from the womb through the whole of their life.",
  },
  {
    stage: "week-22",
    phase: "pregnancy",
    index: 21,
    title: "Week 22 — Small and detailed",
    body: "Fine details are emerging, from wispy eyebrows and lashes to a developing grip in those tiny hands. The baby is looking more and more like the child you will hold. God attends to the smallest things.",
    verse: {
      text: "When I am afraid, I put my trust in you.",
      ref: "Psalm 56:3",
    },
    reflection: "Fear and faith can share the same moment; the question is which one you act on. Trust is a choice you make even while afraid.",
    action: "The next time fear rises, say this verse aloud and turn it into a prayer.",
    partnerFocus: "When she is afraid, do not rush her past it; help her turn the fear into trust. Pray Psalm 56:3 together whenever anxiety comes.",
    prayerPoint: "Ask God to meet you in your fears, and to teach you to trust him each time worry rises.",
  },
  {
    stage: "week-23",
    phase: "pregnancy",
    index: 22,
    title: "Week 23 — Beginning to hear you",
    body: "The baby's hearing is sharpening, and they may begin to respond to familiar voices and sounds. Your words, your songs, and your prayers reach into the womb. A relationship is quietly forming through sound.",
    verse: {
      text: "Fear not, for I have redeemed you; I have called you by name, you are mine.",
      ref: "Isaiah 43:1",
    },
    reflection: "The child who is learning your voice belongs first to the God who calls each of his own by name. Their deepest identity is his, before it is yours.",
    action: "Speak your baby's name, if you have one, or a chosen prayer over them today.",
    partnerFocus: "Read a psalm aloud over the baby regularly so both your voices carry Scripture into the womb. Pray that this child would one day be called by name and redeemed by Christ.",
    prayerPoint: "Ask the Lord to call this child by name and make them his own, redeemed by the blood of Christ.",
  },
  {
    stage: "week-24",
    phase: "pregnancy",
    index: 23,
    title: "Week 24 — Tiny footprints",
    body: "The lungs are developing in preparation for the day the baby will breathe air, and the little feet now bear their own unique prints. The baby is becoming ever more responsive to the world. Life is preparing for its first breath.",
    verse: {
      text: "I lift up my eyes to the hills. From where does my help come? My help comes from the LORD, who made heaven and earth.",
      ref: "Psalm 121:1-2",
    },
    reflection: "When you feel the weight of what is coming, lift your eyes higher than the hills. Your help is not in your own strength but in the Maker of it all.",
    action: "Each morning this week, lift your eyes and name where your help comes from.",
    partnerFocus: "Be a practical help to her body and spirit, and point her again and again to the Lord as your true helper. Pray Psalm 121 over your home.",
    prayerPoint: "Lift your eyes to the Lord, the Maker of heaven and earth, and ask him for the help you cannot supply yourselves.",
  },
  {
    stage: "week-25",
    phase: "pregnancy",
    index: 24,
    title: "Week 25 — Responsive and growing",
    body: "The baby now responds to sound and touch, sometimes shifting when you rest a hand on your belly. Hair is gaining its color, and the little one is filling out steadily. There is a growing back-and-forth between you and your child.",
    verse: {
      text: "And we know that for those who love God all things work together for good, for those who are called according to his purpose.",
      ref: "Romans 8:28",
    },
    reflection: "God is weaving even the hard and hidden parts of this season toward good for those who are his. Good does not always mean easy, but it is always sure.",
    action: "Rest a hand on your belly and thank God for how he is working, even unseen.",
    partnerFocus: "When plans or circumstances are hard, remind her gently that God works all things for good. Pray together, trusting his purposes over your understanding.",
    prayerPoint: "Ask God to work all things, easy and hard, for the good of your family and the glory of his name.",
  },
  {
    stage: "week-26",
    phase: "pregnancy",
    index: 25,
    title: "Week 26 — Eyes begin to open",
    body: "The baby's eyes, long fused shut, are beginning to open for the first time. Though there is little to see in the womb, the readiness for light is being formed. New capacities are quietly awakening.",
    verse: {
      text: "The LORD is near to the brokenhearted and saves the crushed in spirit.",
      ref: "Psalm 34:18",
    },
    reflection: "Whatever this journey has cost you, God draws near to the broken rather than away. He is nearest when you feel least whole.",
    action: "Bring one grief or disappointment honestly to God today, without dressing it up.",
    partnerFocus: "If she is carrying grief or hard news, sit near her in it rather than hurrying her out of it. Pray, asking the Lord to draw near to any brokenness between you.",
    prayerPoint: "Thank God that he is near the brokenhearted, and ask him to hold close any sorrow you carry into this pregnancy.",
  },
  {
    stage: "week-27",
    phase: "pregnancy",
    index: 26,
    title: "Week 27 — A new season begins",
    body: "The third trimester begins, and the baby's brain is remarkably active, forming patterns of sleeping and waking. The little one is growing rounder and stronger by the week. A final stretch of waiting opens before you.",
    verse: {
      text: "Do not be anxious about anything, but in everything by prayer and supplication with thanksgiving let your requests be made known to God.",
      ref: "Philippians 4:6",
    },
    reflection: "As the finish line comes into view, let each new worry become a new prayer. Thanksgiving is what keeps requests from turning into fear.",
    action: "Write out your requests for the coming weeks and turn each one into a prayer.",
    partnerFocus: "Set a regular time to pray through the coming weeks together so worries are met with supplication. Give thanks aloud for how far God has brought you.",
    prayerPoint: "Bring every anxiety about the trimester ahead to God in prayer, with thanksgiving for all he has already done.",
  },
  {
    stage: "week-28",
    phase: "pregnancy",
    index: 27,
    title: "Week 28 — Rest and waking",
    body: "The baby now cycles through periods of sleep and waking, and the eyes can open and close. They may respond to light that reaches the womb and to the rhythms of your day. A little life is settling into patterns of rest.",
    verse: {
      text: "My grace is sufficient for you, for my power is made perfect in weakness.",
      ref: "2 Corinthians 12:9",
    },
    reflection: "You do not need to feel strong to be carried; God's grace meets you precisely in your weakness. Weakness is where his power shows most clearly.",
    action: "Admit one area of weakness to God and ask for his sufficient grace there.",
    partnerFocus: "When she feels weak or tired, do not ask her to be strong; remind her of the grace that is enough. Pray, offering your own weaknesses to God as well.",
    prayerPoint: "Ask the Lord for grace sufficient to your weakness, trusting that his power is made perfect there.",
  },
  {
    stage: "week-29",
    phase: "pregnancy",
    index: 28,
    title: "Week 29 — Steadily maturing",
    body: "The baby's muscles and lungs continue to mature, and the bones are drawing in strength for the days ahead. Movements may feel more deliberate now, even a little crowded. Everything is being made ready in its time.",
    verse: {
      text: "It is the LORD who goes before you. He will be with you; he will not leave you or forsake you. Do not fear or be dismayed.",
      ref: "Deuteronomy 31:8",
    },
    reflection: "Whatever the coming weeks hold, God has already gone ahead of you into them. You are not walking into an unknown; he is there already.",
    action: "Name one uncertainty about the future and trust that God is already there.",
    partnerFocus: "Talk honestly about fears of the days ahead, then remind each other the Lord has gone before you. Pray against fear and dismay in both your hearts.",
    prayerPoint: "Thank God that he goes before your family, and ask him to steady your hearts against fear of what is coming.",
  },
  {
    stage: "week-30",
    phase: "pregnancy",
    index: 29,
    title: "Week 30 — A growing grip",
    body: "The baby's grip is strengthening, and the brain is developing quickly, forming the folds it will keep for life. There is less room to move, so kicks may feel firmer and closer. A capable little person is taking shape.",
    verse: {
      text: "Trust in the LORD with all your heart, and do not lean on your own understanding. In all your ways acknowledge him, and he will make straight your paths.",
      ref: "Proverbs 3:5-6",
    },
    reflection: "You cannot see the whole path, but you can trust the One who does. Straight paths are his work, not yours to engineer.",
    action: "Surrender one plan you have been gripping tightly and acknowledge God in it.",
    partnerFocus: "Help her hold plans loosely by holding them loosely yourself and trusting God together. Pray for wisdom to acknowledge him in every decision ahead.",
    prayerPoint: "Ask God to help you trust him with your whole heart, leaning on his understanding rather than your own.",
  },
  {
    stage: "week-31",
    phase: "pregnancy",
    index: 30,
    title: "Week 31 — Senses awake",
    body: "All five senses are working now, and the baby is taking in the muffled sounds, gentle light, and movements of the world you share. Rapid brain growth continues. The little one is becoming keenly aware.",
    verse: {
      text: "Be still, and know that I am God.",
      ref: "Psalm 46:10",
    },
    reflection: "In a season of much doing and preparing, God calls you first to be still and know him. Stillness is not idleness; it is trust with its hands open.",
    action: "Take five quiet minutes today with no task but to be still before God.",
    partnerFocus: "Protect a pocket of quiet for her amid the preparations, and be still before God with her. Pray simply, without rushing to the next thing on the list.",
    prayerPoint: "Ask God to quiet your striving, that you would be still and truly know that he is God.",
  },
  {
    stage: "week-32",
    phase: "pregnancy",
    index: 31,
    title: "Week 32 — Practicing to breathe",
    body: "The baby is practicing breathing motions and steadily gaining weight, growing rounder and softer. Their movements are strong and often felt throughout the day. Preparation for the first breath continues in earnest.",
    verse: {
      text: "By the word of the LORD the heavens were made, and by the breath of his mouth all their host.",
      ref: "Psalm 33:6",
    },
    reflection: "The breath your child is practicing for is a gift from the God whose breath made the stars. Every breath, first to last, is grace.",
    action: "Thank God for the gift of breath as you take a few slow, deep ones yourself.",
    partnerFocus: "Marvel together at the God who gives breath, and thank him for the child soon to breathe. Pray for calm as the due date draws nearer.",
    prayerPoint: "Praise God who gives breath to all things, and ask him to fill your child's lungs with life at the appointed time.",
  },
  {
    stage: "week-33",
    phase: "pregnancy",
    index: 32,
    title: "Week 33 — Softly cradled",
    body: "The baby's bones are hardening, though the plates of the skull stay soft and separate to ease the journey of birth. The little one is running low on room and curling in close. Tender provision has been made even for the way out.",
    verse: {
      text: "Can a woman forget her nursing child, that she should have no compassion on the son of her womb? Even these may forget, yet I will not forget you.",
      ref: "Isaiah 49:15",
    },
    reflection: "The tender love you feel is a small echo of a love that will never fail or forget. God's love outlasts even a mother's.",
    action: "Let your love for your child point you to God's greater, unfailing love.",
    partnerFocus: "Reassure her of your steadfast love as the birth nears, and point you both to God's love that never forgets. Pray with tenderness over your child.",
    prayerPoint: "Thank God for a love that will never forget his own, and ask that your child would rest in it all their life.",
  },
  {
    stage: "week-34",
    phase: "pregnancy",
    index: 33,
    title: "Week 34 — Small and complete",
    body: "Fingernails have grown to the very tips of the fingers, and the baby looks much as they will at birth, only smaller. The central nervous system and lungs keep maturing. The little one is nearly ready.",
    verse: {
      text: "Blessed be the God and Father of our Lord Jesus Christ, the Father of mercies and God of all comfort.",
      ref: "2 Corinthians 1:3",
    },
    reflection: "Whatever comfort you need in these final weeks, it flows from the Father of all mercies. He comforts not so you would forget the trouble, but so you would know him in it.",
    action: "Receive God's comfort in one weary place, and thank him as the Father of mercies.",
    partnerFocus: "Be a channel of God's comfort to her in the tiring final stretch, patient and gentle. Pray, receiving comfort from the Father together.",
    prayerPoint: "Bless the Father of mercies, and ask him for his comfort in every weariness of these last weeks.",
  },
  {
    stage: "week-35",
    phase: "pregnancy",
    index: 34,
    title: "Week 35 — Filling out",
    body: "The baby is filling out with soft rounded cheeks and a fuller frame, and the kidneys and other organs are fully developed. Most of the major growing is done; now it is about final readiness. The little one is nearly complete.",
    verse: {
      text: "Fear not, for I am with you; be not dismayed, for I am your God; I will strengthen you, I will help you, I will uphold you with my righteous right hand.",
      ref: "Isaiah 41:10",
    },
    reflection: "As the day approaches, God's answer to your fear is not a promise of ease but his own presence. He does not merely send help; he comes himself.",
    action: "When fear of the birth rises, hold onto God's promise to be with you.",
    partnerFocus: "Reassure her of your steady presence and God's, especially as anxiety about labor grows. Pray Isaiah 41:10 over her by name.",
    prayerPoint: "Ask God to be with you and uphold you, replacing fear of the days ahead with trust in his presence.",
  },
  {
    stage: "week-36",
    phase: "pregnancy",
    index: 35,
    title: "Week 36 — Settling into place",
    body: "The baby is often settling head-down and dropping lower in readiness for birth. Cheeks are plump now from the developing sucking muscles. The little one is quietly getting into position for the day ahead.",
    verse: {
      text: "He will tend his flock like a shepherd; he will gather the lambs in his arms; he will carry them in his bosom, and gently lead those that are with young.",
      ref: "Isaiah 40:11",
    },
    reflection: "God has a special gentleness for mothers with young, leading you at a pace you can bear. He does not drive the ones who carry lambs; he leads them softly.",
    action: "Let yourself move gently this week, and thank God for leading you gently too.",
    partnerFocus: "Match your pace to hers now; do not push her, but shepherd her gently. Pray, thanking God for leading those who are with young.",
    prayerPoint: "Thank the Good Shepherd for his gentleness with mothers, and ask him to lead your family softly through these final weeks.",
  },
  {
    stage: "week-37",
    phase: "pregnancy",
    index: 36,
    title: "Week 37 — Nearly ready",
    body: "The baby is considered early term now and continues practicing breathing and swallowing. Fat is being added for warmth in the world outside. Nearly everything is ready for the meeting to come.",
    verse: {
      text: "Do not be anxious about tomorrow, for tomorrow will be anxious for itself. Sufficient for the day is its own trouble.",
      ref: "Matthew 6:34",
    },
    reflection: "You cannot live tomorrow's labor today; God gives grace for one day at a time. Meet only the trouble that has actually arrived.",
    action: "Set down tomorrow's worries and ask God for grace enough for today alone.",
    partnerFocus: "Help her stay in today rather than borrowing tomorrow's fears, one day at a time. Pray for grace sufficient for each day until the birth.",
    prayerPoint: "Ask God for grace to face each day as it comes, without borrowing worry from tomorrow.",
  },
  {
    stage: "week-38",
    phase: "pregnancy",
    index: 37,
    title: "Week 38 — Ready and waiting",
    body: "The baby has a firm grasp and organs prepared for life outside the womb. Now it is largely a matter of waiting for the appointed time. Everything that can be made ready has been made ready.",
    verse: {
      text: "Know that the LORD, he is God! It is he who made us, and we are his; we are his people, and the sheep of his pasture.",
      ref: "Psalm 100:3",
    },
    reflection: "This child was made by God and belongs to God before they ever belong to you. You will hold what is ultimately his.",
    action: "Entrust your child to God today, remembering they are his before they are yours.",
    partnerFocus: "Talk together about holding this child with open hands, as God's before yours. Pray, dedicating the child to the Lord who made them.",
    prayerPoint: "Acknowledge that this child belongs to God, and ask for grace to receive and raise them as his own.",
  },
  {
    stage: "week-39",
    phase: "pregnancy",
    index: 38,
    title: "Week 39 — Full term",
    body: "The baby is now full term, fully formed and simply growing and resting until birth. Any day now, the waiting may give way to meeting. The little one you have carried is nearly in your arms.",
    verse: {
      text: "Every good gift and every perfect gift is from above, coming down from the Father of lights.",
      ref: "James 1:17",
    },
    reflection: "The child soon to be placed in your arms is a good and perfect gift from above. Receive them as grace, not as reward.",
    action: "Prepare your heart to receive your child as a gift, not something you earned.",
    partnerFocus: "Ready the home and your own heart to welcome this gift with gratitude, not pressure. Pray, thanking the Father of lights for the child about to come.",
    prayerPoint: "Thank God for the good gift about to be given, and ask for hearts ready to receive your child with joy and thanks.",
  },
  {
    stage: "week-40",
    phase: "pregnancy",
    index: 39,
    title: "Week 40 — The appointed time",
    body: "You have reached the due date, though babies keep their own timing. Soon the long season of waiting will give way to labor and to the first sight of your child's face. Joy is drawing near, on the other side of the work.",
    verse: {
      text: "When a woman is giving birth, she has sorrow because her hour has come, but when she has delivered the baby, she no longer remembers the anguish, for joy that a human being has been born into the world.",
      ref: "John 16:21",
    },
    reflection: "The hard hour ahead is real, and so is the joy that will follow it. God does not spare you the labor, but he does not waste it either.",
    action: "Commit the labor to the Lord, asking for his strength and presence through it.",
    partnerFocus: "Be fully present through labor, encouraging and steady, ready to serve rather than to be served. Pray over her for strength, and for the safe arrival of your child.",
    prayerPoint: "Ask God for his strength and nearness through labor and birth, and for joy on the far side of the sorrow.",
  },
  {
    stage: "month-0",
    phase: "infancy",
    index: 40,
    title: "Month 0 — The fourth trimester",
    body: "Your newborn is here, curled and sleepy, still learning the wide world after the snugness of the womb. Days and nights blur together as feeding, soothing, and holding fill nearly every hour. This tender, foggy season is its own kind of holy ground.",
    verse: {
      text: "For this child I prayed, and the LORD has granted me my petition that I made to him.",
      ref: "1 Samuel 1:27",
    },
    reflection: "The child in your arms is an answered prayer, whatever the exhaustion of these first days. Grace does not stop being grace because it is tiring.",
    action: "Hold your baby close and give them back to God in a simple prayer of thanks.",
    partnerFocus: "Take night duties and household work off her plate so she can recover and feed; guard her rest fiercely. Pray thanks together over the child God has granted you.",
    prayerPoint: "Thank the Lord for granting this child, and ask him for strength and grace through the sleepless fourth trimester.",
  },
  {
    stage: "month-1",
    phase: "infancy",
    index: 41,
    title: "Month 1 — Learning your face",
    body: "Your baby is beginning to focus on faces and may offer the first tiny coos. They are comforted most by being held, fed, and hearing your voice. Slowly, a small person is learning that the world is a safe place to be.",
    verse: {
      text: "But I have calmed and quieted my soul, like a weaned child with its mother; like a weaned child is my soul within me.",
      ref: "Psalm 131:2",
    },
    reflection: "As your baby learns to be calmed by you, learn to be calmed by God. A quieted soul is not one without trouble, but one that has found where to rest.",
    action: "When you soothe your baby, breathe a prayer asking God to quiet your own soul.",
    partnerFocus: "Keep serving her practically and speak calm into the tired days rather than adding pressure. Pray for quieted souls in a home short on sleep.",
    prayerPoint: "Ask God to calm and quiet your souls as you learn to calm your child, resting in him like a contented child.",
  },
  {
    stage: "month-2",
    phase: "infancy",
    index: 42,
    title: "Month 2 — The first true smiles",
    body: "Around now your baby may give their first real, responsive smiles, lighting up at the sight of you. Sleep may begin to gather into slightly longer stretches, though rhythms are still forming. Every smile is a small gift of connection.",
    verse: {
      text: "In peace I will both lie down and sleep; for you alone, O LORD, make me dwell in safety.",
      ref: "Psalm 4:8",
    },
    reflection: "In a season measured by sleep you rarely get, God alone is the one who keeps you safe through the night. Your security rests in his watch, not your rest.",
    action: "As you lay your baby down, entrust both of you to God's keeping through the night.",
    partnerFocus: "Share the night waking so she is not always the one to rise, and pray over the baby's sleep together. Ask God for rest and peace in a weary house.",
    prayerPoint: "Thank God who keeps you safe as you sleep, and ask him for peace and rest through the long nights.",
  },
  {
    stage: "month-3",
    phase: "infancy",
    index: 43,
    title: "Month 3 — Coos and laughter",
    body: "Your baby is finding their voice with coos and gurgles, and the first laughs may bubble up. They hold their head steadier now and love watching the people around them. Their little personality is beginning to shine through.",
    verse: {
      text: "As a father shows compassion to his children, so the LORD shows compassion to those who fear him.",
      ref: "Psalm 103:13",
    },
    reflection: "The tenderness you feel toward your child is a window into God's compassion toward you. He is not a distant judge but a compassionate Father.",
    action: "Let your compassion for your child remind you to receive the Father's compassion.",
    partnerFocus: "As a father, show tender compassion to both mother and child, modeling the Father's heart. Pray to reflect God's fatherly care in your home.",
    prayerPoint: "Thank God for his fatherly compassion, and ask him to shape your parenting into a picture of his own tenderness.",
  },
  {
    stage: "month-4",
    phase: "infancy",
    index: 44,
    title: "Month 4 — Reaching out",
    body: "Your baby is reaching for things, grasping at faces and toys, and may be starting to roll. They are increasingly curious about the world and delighted by play. Their growing awareness is a good time to begin small rhythms of family worship.",
    verse: {
      text: "And these words that I command you today shall be on your heart. You shall teach them diligently to your children, and shall talk of them when you sit in your house, and when you walk by the way, and when you lie down, and when you rise.",
      ref: "Deuteronomy 6:6-7",
    },
    reflection: "Discipleship is not a program but a texture woven through ordinary days. Before your child understands the words, they will absorb the rhythm.",
    action: "Begin a short daily habit of reading a verse and praying together as a family.",
    partnerFocus: "Take the lead in starting family worship, even if it is only two minutes a day, and keep it going. Pray for consistency in teaching your child the Word.",
    prayerPoint: "Ask God to help you fill your home and ordinary days with his Word, teaching your child diligently from the start.",
  },
  {
    stage: "month-5",
    phase: "infancy",
    index: 45,
    title: "Month 5 — Grabbing the world",
    body: "Your baby grabs at everything within reach and brings much of it to their mouth to explore. They may sit with support and babble in strings of sounds. This is a season of eager discovery, and of parents telling of God's works aloud.",
    verse: {
      text: "We will not hide them from their children, but tell to the coming generation the glorious deeds of the LORD, and his might, and the wonders that he has done.",
      ref: "Psalm 78:4",
    },
    reflection: "Long before your child can understand doctrine, they can hear you speak of God's goodness with joy. The next generation learns to treasure what they hear us treasure.",
    action: "Tell your baby out loud one thing God has done, as if passing on a story.",
    partnerFocus: "Speak of God's deeds within your child's hearing, and keep telling one another his faithfulness too. Pray to be a generation that does not hide the Lord from the next.",
    prayerPoint: "Ask God for grace to tell your child of his mighty deeds, so the coming generation would know and love him.",
  },
  {
    stage: "month-6",
    phase: "infancy",
    index: 46,
    title: "Month 6 — Sitting up to see",
    body: "Your baby may sit up on their own now, taking in the world from a new vantage point, and could be trying first tastes of solid food. Half a year of growth is behind you. Bring this little one into the family's worship, even as an observer in arms.",
    verse: {
      text: "Let the children come to me; do not hinder them, for to such belongs the kingdom of God.",
      ref: "Mark 10:14",
    },
    reflection: "Jesus welcomes the smallest children; so should our homes and worship. No one is too young to be brought near to Christ.",
    action: "Include your baby in a time of worship this week, held close as you sing.",
    partnerFocus: "Make sure the baby is welcomed into worship rather than kept apart, and help her not feel she must hide away. Pray that your child would come to Christ.",
    prayerPoint: "Thank Jesus for welcoming little children, and ask that your child would be drawn to him from their earliest days.",
  },
  {
    stage: "month-7",
    phase: "infancy",
    index: 47,
    title: "Month 7 — On the move",
    body: "Your baby may be babbling in longer strings and beginning to scoot or crawl toward what they want. They are learning cause and effect, testing what happens when they act. Gentle, consistent guidance begins to matter now.",
    verse: {
      text: "Train up a child in the way he should go; even when he is old he will not depart from it.",
      ref: "Proverbs 22:6",
    },
    reflection: "Training is patient and long, aimed not at this moment only but at the whole of a life. You are laying grooves your child may run in for years to come.",
    action: "Set one gentle, consistent boundary and hold it kindly this week.",
    partnerFocus: "Agree together on how you will guide the baby so you are consistent, not divided. Pray for patience and wisdom as training begins.",
    prayerPoint: "Ask God for wisdom to train your child in his ways, trusting the long, slow work of faithful parenting to him.",
  },
  {
    stage: "month-8",
    phase: "infancy",
    index: 48,
    title: "Month 8 — Pulling to stand",
    body: "Your baby may pull up to standing and grow more aware of who is familiar and who is not, sometimes clinging when strangers come near. They are bonding deeply with you. This closeness is a good reminder of who truly holds your home together.",
    verse: {
      text: "Unless the LORD builds the house, those who build it labor in vain.",
      ref: "Psalm 127:1",
    },
    reflection: "All your efforts to build a strong family come to nothing unless God is the builder. Work hard, but rest in the fact that the outcome is his.",
    action: "Commit your homebuilding to God, admitting you cannot do it in your own strength.",
    partnerFocus: "Work hard for your family while confessing together that God alone builds the house. Pray, laying your parenting efforts before him.",
    prayerPoint: "Ask the Lord to build your house himself, so that your labor as parents would not be in vain.",
  },
  {
    stage: "month-9",
    phase: "infancy",
    index: 49,
    title: "Month 9 — First words forming",
    body: "Your baby may be pointing, waving, and shaping their first word-like sounds, perhaps a mama or dada. They understand far more than they can say. What they hear from your lips is filling the well they will one day draw speech from.",
    verse: {
      text: "Let the words of my mouth and the meditation of my heart be acceptable in your sight, O LORD, my rock and my redeemer.",
      ref: "Psalm 19:14",
    },
    reflection: "As your child gathers their first words, consider the words that fill your home. What they hear you say most will shape what they learn to treasure.",
    action: "Choose a short Scripture phrase to say often so it becomes familiar in your home.",
    partnerFocus: "Watch your own words in the home, since little ears are learning to speak from them. Pray that your words and hearts would be pleasing to God.",
    prayerPoint: "Ask God to make the words of your mouths acceptable to him, so your child learns speech shaped by grace.",
  },
  {
    stage: "month-10",
    phase: "infancy",
    index: 50,
    title: "Month 10 — Little understandings",
    body: "Your baby is beginning to grasp simple words like no and bye, and may wave or clap on cue. Their reasoning is still that of a small child, wonderfully concrete. Meet them where they are, gently and patiently.",
    verse: {
      text: "When I was a child, I spoke like a child, I thought like a child, I reasoned like a child.",
      ref: "1 Corinthians 13:11",
    },
    reflection: "God is patient with our childlike understanding, and calls us to the same patience. Your child cannot reason as an adult yet, and does not need to.",
    action: "Lower your expectations to your child's age today and respond with patience.",
    partnerFocus: "Remind each other that a baby will act like a baby, and extend patience when tired. Pray for grace to meet your child at their level.",
    prayerPoint: "Ask God for patience with your child's small understanding, remembering his patience with your own.",
  },
  {
    stage: "month-11",
    phase: "infancy",
    index: 51,
    title: "Month 11 — Cruising along",
    body: "Your baby may be cruising along the furniture and standing with more confidence, edging toward those first independent steps. All this activity can leave parents worn thin. In the tiredness, God renews the strength of those who wait on him.",
    verse: {
      text: "But they who wait for the LORD shall renew their strength; they shall mount up with wings like eagles; they shall run and not be weary; they shall walk and not faint.",
      ref: "Isaiah 40:31",
    },
    reflection: "The strength you lack is not manufactured but received, given fresh to those who wait on the Lord. Waiting on him is not passive; it is where renewal comes.",
    action: "When you feel depleted, pause to wait quietly on the Lord for renewed strength.",
    partnerFocus: "Notice when she is running on empty and step in so she can rest and wait on God. Pray for renewed strength for both of you.",
    prayerPoint: "Ask the Lord to renew your strength as you wait on him through the demands of this season.",
  },
  {
    stage: "month-12",
    phase: "infancy",
    index: 52,
    title: "Month 12 — The first year complete",
    body: "Your baby may be taking first steps and saying a few clear words as they reach their first birthday. A whole year of growth and grace lies behind you. This little one is growing in body and, by God's kindness, in favor.",
    verse: {
      text: "Now the boy Samuel continued to grow both in stature and in favor with the LORD and also with man.",
      ref: "1 Samuel 2:26",
    },
    reflection: "Look back over a year of small daily faithfulness and see how God has grown your child. What felt like ordinary days added up to a year of grace.",
    action: "Mark the first birthday by thanking God for a year of his faithfulness.",
    partnerFocus: "Celebrate the year together and honor her labor of love through it. Pray, thanking God for your child's growth in stature and favor.",
    prayerPoint: "Thank God for a year of grace, and ask that your child would grow in favor with the Lord and with people.",
  },
  {
    stage: "month-13",
    phase: "infancy",
    index: 53,
    title: "Month 13 — Toddling forward",
    body: "Your little one is toddling with growing confidence and exploring everything within reach. New words and gestures appear almost daily. The family table is becoming a place where this little shoot grows up among you.",
    verse: {
      text: "Your children will be like olive shoots around your table.",
      ref: "Psalm 128:3",
    },
    reflection: "The family table is a small nursery for growing souls, gathered close around you. Ordinary meals become the soil where children take root.",
    action: "Gather for a shared meal this week and pray together at the table.",
    partnerFocus: "Protect regular family meals as a place of togetherness and prayer, not just food. Pray over your child as an olive shoot God is growing.",
    prayerPoint: "Thank God for your child growing up around your table, and ask him to root them deeply in your family's faith.",
  },
  {
    stage: "month-14",
    phase: "infancy",
    index: 54,
    title: "Month 14 — Watching and copying",
    body: "Your toddler is a keen imitator now, copying your words, gestures, and even your tone of voice. They are learning how to live by watching how you live. What they see in you teaches more than anything you say.",
    verse: {
      text: "Even a child makes himself known by his acts, by whether his conduct is pure and upright.",
      ref: "Proverbs 20:11",
    },
    reflection: "Your child is learning godliness less from your instructions than from your example. They will imitate the life they see, not merely the words they hear.",
    action: "Choose one habit you want your child to imitate and practice it deliberately.",
    partnerFocus: "Hold each other kindly accountable to live what you hope your child will copy. Pray for integrity, since little eyes are always watching.",
    prayerPoint: "Ask God to make your own conduct pure and upright, so your child learns godliness by watching your lives.",
  },
  {
    stage: "month-15",
    phase: "infancy",
    index: 55,
    title: "Month 15 — Words on the rise",
    body: "Your toddler's vocabulary is growing, and they are eager to name the world around them. They test limits and feelings with equal energy. Loving discipline and instruction now go hand in hand.",
    verse: {
      text: "Fathers, do not provoke your children to anger, but bring them up in the discipline and instruction of the Lord.",
      ref: "Ephesians 6:4",
    },
    reflection: "Discipline is not the opposite of love but one of its truest forms, aimed always at the child's good. It is nurture, not merely correction.",
    action: "Pair any correction this week with warmth, so discipline and love stay joined.",
    partnerFocus: "As a father, lead in gentle discipline that never provokes but always instructs. Pray together for wisdom to correct without exasperating.",
    prayerPoint: "Ask God to help you discipline and instruct your child in his ways, without provoking them to anger.",
  },
  {
    stage: "month-16",
    phase: "infancy",
    index: 56,
    title: "Month 16 — Big feelings",
    body: "Your toddler feels things strongly and may not yet have words for the storms inside them, so frustration can spill into tears or tantrums. This is normal and not a sign of failure. It is a tender place to teach the heart with patience.",
    verse: {
      text: "Folly is bound up in the heart of a child, but the rod of discipline drives it far from him.",
      ref: "Proverbs 22:15",
    },
    reflection: "Your child's struggles are not surprising; folly is bound up in every human heart, including your own. Loving correction is part of shepherding, not rejecting, your child.",
    action: "When a hard moment comes, respond with patient correction rather than anger.",
    partnerFocus: "Support her steadiness on the hard days and take your turn when her patience runs low. Pray for gentleness and consistency through the tantrum season.",
    prayerPoint: "Ask God for patient, loving wisdom to shepherd your child's heart, addressing folly without harshness.",
  },
  {
    stage: "month-17",
    phase: "infancy",
    index: 57,
    title: "Month 17 — Testing and tender",
    body: "Your toddler swings between fierce independence and needing your comfort, often within the same minute. They are learning how to handle big emotions with small resources. Your steady, gentle presence teaches them more than any lecture.",
    verse: {
      text: "Fathers, do not provoke your children, lest they become discouraged.",
      ref: "Colossians 3:21",
    },
    reflection: "Discipline that crushes rather than shepherds leaves a child discouraged. Aim to correct in a way that builds up and never breaks the spirit.",
    action: "Check that your corrections build your child up rather than wear them down.",
    partnerFocus: "Watch each other for weariness that turns to harshness and gently call it out. Pray not to discourage your child in the tiring in-between days.",
    prayerPoint: "Ask God to keep your discipline from provoking or discouraging your child, so their spirit stays tender toward you and toward him.",
  },
  {
    stage: "month-18",
    phase: "infancy",
    index: 58,
    title: "Month 18 — Off and running",
    body: "Your child is likely walking well and may be running, climbing, and exploring with fearless energy. Their world is expanding fast, and so is their will. These little ones are arrows being carefully aimed for years to come.",
    verse: {
      text: "Like arrows in the hand of a warrior are the children of one's youth.",
      ref: "Psalm 127:4",
    },
    reflection: "Children are arrows meant to be aimed and released, not kept forever on the string. Even now you are shaping a life meant one day to fly.",
    action: "Pray with the long view, asking God to aim your child's life toward his purposes.",
    partnerFocus: "Talk together about the direction you are aiming your child, not just today's behavior. Pray over your child as an arrow being readied for God's purposes.",
    prayerPoint: "Ask God to help you aim your child's life toward him, shaping them now for the good he has prepared.",
  },
  {
    stage: "month-19",
    phase: "infancy",
    index: 59,
    title: "Month 19 — Make-believe begins",
    body: "Your toddler is beginning to pretend, feeding a doll or talking on a toy phone, a sign of a growing imagination. They come to the world with wide-eyed trust and wonder. There is much to learn from the simple, dependent faith of a small child.",
    verse: {
      text: "Truly, I say to you, unless you turn and become like children, you will never enter the kingdom of heaven.",
      ref: "Matthew 18:3",
    },
    reflection: "Jesus points to the trust and lowliness of children as the shape of true faith. Your child's simple dependence is a picture of how God calls you to come to him.",
    action: "Watch your child's easy trust today and ask God for that same childlike faith.",
    partnerFocus: "Learn from your child's simple trust and encourage each other toward that same faith. Pray to come to God with childlike dependence, not grown-up self-reliance.",
    prayerPoint: "Ask God for a childlike faith in your own hearts, and that your child would keep trusting him simply as they grow.",
  },
  {
    stage: "month-20",
    phase: "infancy",
    index: 60,
    title: "Month 20 — A growing memory",
    body: "Your toddler remembers routines, people, and favorite stories, and loves the comfort of repetition. Their memory is a fertile field for the truths you plant. What you teach now can take root and last.",
    verse: {
      text: "Make them known to your children and your children's children.",
      ref: "Deuteronomy 4:9",
    },
    reflection: "The truths you repeat now are being stored for a lifetime and beyond. You are teaching not only your child but generations you may never meet.",
    action: "Repeat a simple truth about God until it becomes familiar to your child.",
    partnerFocus: "Choose together a few core truths to teach again and again through repetition. Pray, with the coming generations in view.",
    prayerPoint: "Ask God to help you make his truth known to your child and their children after them.",
  },
  {
    stage: "month-21",
    phase: "infancy",
    index: 61,
    title: "Month 21 — Little choices",
    body: "Your toddler is asserting preferences and making small choices, discovering they have a will of their own. This growing independence is an opportunity to model whom your family serves. Even small daily choices point toward larger loyalties.",
    verse: {
      text: "But as for me and my house, we will serve the LORD.",
      ref: "Joshua 24:15",
    },
    reflection: "Your child will learn what it means to serve the Lord largely by watching your household do it. The choice is renewed daily, in ordinary decisions.",
    action: "Name aloud one way your family chooses to serve the Lord this week.",
    partnerFocus: "Recommit together to leading a household that serves the Lord, in decisions large and small. Pray for a home marked by that resolve.",
    prayerPoint: "Ask God to make your household one that serves him, so your child grows up in that daily commitment.",
  },
  {
    stage: "month-22",
    phase: "infancy",
    index: 62,
    title: "Month 22 — Stringing words together",
    body: "Your toddler is beginning to put two or three words together into little sentences, telling you more of what they see and want. Language is opening up their inner world. The faith you live is being passed into a heart that is starting to speak.",
    verse: {
      text: "I am reminded of your sincere faith, a faith that dwelt first in your grandmother Lois and your mother Eunice.",
      ref: "2 Timothy 1:5",
    },
    reflection: "Faith is often handed down through ordinary, sincere households across generations. The quiet faith of parents becomes the inheritance of children.",
    action: "Tell your child a simple story of God's faithfulness in your own family.",
    partnerFocus: "Talk about the faith you both want to pass on and how your home is passing it now. Pray for a sincere faith that dwells in your family across generations.",
    prayerPoint: "Ask God to plant a sincere faith in your child, passed down through a home that truly trusts him.",
  },
  {
    stage: "month-23",
    phase: "infancy",
    index: 63,
    title: "Month 23 — Hungry for stories",
    body: "Your toddler loves stories now, asking for the same ones again and again and soaking up every word. This appetite is a gift and an open door. It is a fitting time to make the Scriptures a familiar and beloved part of their days.",
    verse: {
      text: "From childhood you have been acquainted with the sacred writings, which are able to make you wise for salvation through faith in Christ Jesus.",
      ref: "2 Timothy 3:15",
    },
    reflection: "The Scriptures your child hears now can make them wise for salvation later. You are not merely reading stories; you are sowing seeds of eternal life.",
    action: "Read a simple Bible story to your child as part of your daily rhythm.",
    partnerFocus: "Make Scripture reading a regular joy in your home, taking turns telling its stories. Pray that these sacred writings would make your child wise for salvation.",
    prayerPoint: "Ask God to acquaint your child with his Word from childhood, making them wise for salvation through faith in Christ.",
  },
  {
    stage: "month-24",
    phase: "infancy",
    index: 64,
    title: "Month 24 — Two years of grace",
    body: "Your child is full of words, will, and wonder as they reach two years old. Every day they grow in body, mind, and understanding. Like the Lord Jesus in his childhood, they grow in stature and, by grace, in favor with God and people.",
    verse: {
      text: "And Jesus increased in wisdom and in stature and in favor with God and man.",
      ref: "Luke 2:52",
    },
    reflection: "Even the Son of God grew as a child, through ordinary years of increasing wisdom and favor. Your child's slow growth is holy ground, and God is at work in every step.",
    action: "Look back over two years and thank God for how he has grown your whole family.",
    partnerFocus: "Celebrate two years together and cast a shared vision for the years of discipleship ahead. Pray that your child would increase in wisdom and in favor with God and man.",
    prayerPoint: "Thank God for two years of grace, and ask that your child would grow like Christ in wisdom, stature, and favor.",
  },
];

export const PREGNANCY_STAGES = STAGES.filter((s) => s.phase === "pregnancy");
export const INFANCY_STAGES = STAGES.filter((s) => s.phase === "infancy");

export function stageBySlug(slug: string): Stage | undefined {
  return STAGES.find((s) => s.stage === slug);
}
