import { ImageResponse } from "next/og";
import { plainLinks } from "@/lib/linkify";
import { getPublicInvitation } from "@/lib/invitations-db";
import { longDay, timeRange } from "@/lib/invitations";

export const runtime = "nodejs";
export const alt = "An invitation from Oyun";
export const size = { width: 1200, height: 630 };
export const contentType = "image/png";

/**
 * What the link looks like in WhatsApp.
 *
 * This decides whether anybody taps it. A bare link with no preview reads as
 * something forwarded from a stranger, and in a family group chat it gets
 * ignored. A card with the party's name and the date on it reads as an
 * invitation, which is what it is.
 *
 * It carries the title, the day and the place — everything already on the
 * public page — and nothing more. A link preview is generated by WhatsApp's
 * servers and cached who knows where, so it is the wrong place for anything
 * she would not want repeated.
 *
 * ── The host's photograph, when there is one ─────────────────────────────
 * It becomes the background, behind a scrim heavy enough that the words
 * survive whatever the picture turns out to be. The scrim is not a style
 * choice: this card is composed once and then shown at thumbnail size over
 * somebody's chat wallpaper, and white type on an unknown photograph is
 * unreadable about half the time.
 */

function truncate(s: string, n: number): string {
  return s.length > n ? `${s.slice(0, n - 1).trimEnd()}…` : s;
}

/**
 * A second and a half, two megabytes, and an image or nothing.
 *
 * Deliberately mean. WhatsApp fetches this card while somebody waits for a
 * message to send, and it gives up quickly — so a card that arrives late is
 * a card that does not arrive, and a link goes out with no picture on it at
 * all. A plain card is a good outcome; no card is the bad one. Every budget
 * here is set so that the worst case is the plain card.
 *
 * Covers that go through the app are shrunk before they are uploaded, so two
 * megabytes is generous for anything chosen the ordinary way.
 */
const FETCH_MS = 1500;
const MAX_BYTES = 2 * 1024 * 1024;

/**
 * The photograph, as bytes we already hold.
 *
 * ── Why it is fetched here instead of passed as a URL ────────────────────
 * Because `<img src="https://…">` inside an ImageResponse is fetched while
 * the picture is being drawn, and a slow or missing file there fails the
 * whole route — after the response has begun. The card would not fall back
 * to the plain design; it would simply not arrive, and the invitation would
 * go out as a bare link, which is the one outcome this file exists to
 * prevent.
 *
 * Fetching first makes the failure ordinary: no bytes, no photograph, and
 * the card that worked before this feature existed.
 */
async function photograph(url: string | null): Promise<string | null> {
  if (!url) return null;
  try {
    const res = await fetch(url, { signal: AbortSignal.timeout(FETCH_MS) });
    if (!res.ok) return null;

    const type = res.headers.get("content-type") ?? "";
    if (!type.startsWith("image/")) return null;

    const declared = Number(res.headers.get("content-length") ?? 0);
    if (declared > MAX_BYTES) return null;

    const buf = Buffer.from(await res.arrayBuffer());
    // Checked again: content-length is a claim, and a server that lies about
    // it would otherwise put the whole file in memory anyway.
    if (buf.byteLength === 0 || buf.byteLength > MAX_BYTES) return null;

    return `data:${type};base64,${buf.toString("base64")}`;
  } catch {
    // Timed out, refused, deleted, DNS — all the same answer here.
    return null;
  }
}

export default async function Image({ params }: { params: { slug: string } }) {
  const i = await getPublicInvitation(params.slug);

  const title = i ? truncate(i.event.title, 80) : "An invitation";
  const day = i ? longDay(i.event.at) : "";
  const hours = i ? timeRange(i.event.at, i.event.hasTime, i.event.endsAt) : "";
  // A link in the location reads as a wall of characters on a picture
  // nobody can tap, so it is shortened to the host-and-path form the page
  // shows. The card is for recognising the invitation, not for using it.
  const where = i?.event.where ? truncate(plainLinks(i.event.where), 60) : "";
  const from = i ? `From ${truncate(i.hostName, 40)}` : "";

  // Same rule as the page: no photograph above a day that was called off.
  const cover = await photograph(
    i && !i.event.cancelled ? i.coverUrl : null,
  );

  return new ImageResponse(
    (
      <div
        style={{
          position: "relative",
          width: "100%",
          height: "100%",
          display: "flex",
          flexDirection: "column",
          justifyContent: "space-between",
          padding: "72px 80px",
          background: "#0B0E14",
          color: "#ECE8DE",
        }}
      >
        {cover && (
          // Sized in pixels, not percentages. Satori resolves `100%` on an
          // absolutely positioned child against nothing useful here, so the
          // photograph came out letterboxed with the card's own background
          // showing down two edges — which looked exactly like a broken
          // image. The canvas is a fixed 1200x630; say so.
          <img
            src={cover}
            alt=""
            width={size.width}
            height={size.height}
            style={{
              position: "absolute",
              top: 0,
              left: 0,
              width: size.width,
              height: size.height,
              objectFit: "cover",
            }}
          />
        )}
        {cover && (
          <div
            style={{
              position: "absolute",
              top: 0,
              left: 0,
              width: size.width,
              height: size.height,
              // Heavier at the foot, where the words are, and never fully
              // clear at the top — a pale sky behind pale type is the common
              // way this sort of card becomes unreadable.
              background:
                "linear-gradient(to bottom, rgba(11,14,20,0.70) 0%, rgba(11,14,20,0.78) 42%, rgba(11,14,20,0.94) 100%)",
            }}
          />
        )}

        <div
          style={{
            position: "relative",
            display: "flex",
            alignItems: "center",
            gap: 18,
          }}
        >
          <svg width="52" height="52" viewBox="0 0 120 120">
            <g transform="translate(60,60)">
              <circle cx="0" cy="0" r="52" fill="none" stroke="#ECE8DE" strokeWidth="4.5" opacity="0.4" />
              <circle cx="0" cy="0" r="34" fill="none" stroke="#ECE8DE" strokeWidth="4.5" opacity="0.72" />
              <circle cx="0" cy="0" r="9" fill="#E6A94E" />
              <circle cx="0" cy="-34" r="5.6" fill="#E6A94E" />
              <circle cx="29.4" cy="17" r="5.6" fill="#E6A94E" />
              <circle cx="-29.4" cy="17" r="5.6" fill="#E6A94E" />
            </g>
          </svg>
          <div
            style={{
              fontSize: 26,
              // On a photograph the grey disappears; on the plain card it is
              // the quiet line it has always been.
              color: cover ? "#D8D3C6" : "#8C93A3",
              letterSpacing: 4,
            }}
          >
            {from.toUpperCase()}
          </div>
        </div>

        <div
          style={{ position: "relative", display: "flex", flexDirection: "column" }}
        >
          <div
            style={{
              fontSize: 72,
              fontFamily: "serif",
              lineHeight: 1.12,
              maxWidth: 1040,
            }}
          >
            {title}
          </div>
          <div style={{ fontSize: 38, fontFamily: "serif", marginTop: 26 }}>
            {day}
          </div>
          {(hours || where) && (
            <div
              style={{
                fontSize: 26,
                color: "#E6A94E",
                letterSpacing: 5,
                textTransform: "uppercase",
                marginTop: 14,
              }}
            >
              {[hours, where].filter(Boolean).join("  ·  ")}
            </div>
          )}
        </div>

        <div
          style={{
            position: "relative",
            fontSize: 24,
            color: cover ? "#D8D3C6" : "#8C93A3",
          }}
        >
          Tap to say whether you can come · Oyun
        </div>
      </div>
    ),
    {
      ...size,
      // ── Why this header is set by hand ─────────────────────────────
      // Next's default for a metadata image is
      // `public, immutable, max-age=31536000` — keep it for a year, it will
      // never change. True of an image whose URL carries a content hash,
      // and false of ours: an invitation's card lives at one address before
      // and after the host picks a photograph. WhatsApp fetched the plain
      // card the first time the link was sent, was told to keep it for a
      // year, and did.
      //
      // So: fresh to the browser, a day on the CDN, and servable while it
      // revalidates. A card that is an hour stale is nobody's problem; a
      // card that is a year stale is the bug this replaces.
      headers: {
        "cache-control":
          "public, max-age=0, s-maxage=86400, stale-while-revalidate=604800",
      },
    },
  );
}
