import { ImageResponse } from "next/og";
import { plainLinks } from "@/lib/linkify";
import { getPublicInvitation } from "@/lib/invitations-db";
import { longDay, timeRange } from "@/lib/invitations";

export const runtime = "nodejs";
export const alt = "An invitation from Oyun";
export const size = { width: 1200, height: 630 };
export const contentType = "image/png";

/**
 * What the link looks like in WhatsApp.
 *
 * This decides whether anybody taps it. A bare link with no preview reads as
 * something forwarded from a stranger, and in a family group chat it gets
 * ignored. A card with the party's name and the date on it reads as an
 * invitation, which is what it is.
 *
 * It carries the title, the day and the place — everything already on the
 * public page — and nothing more. A link preview is generated by WhatsApp's
 * servers and cached who knows where, so it is the wrong place for anything
 * she would not want repeated.
 *
 * ── The host's photograph, when there is one ─────────────────────────────
 * It becomes the background, behind a scrim heavy enough that the words
 * survive whatever the picture turns out to be. The scrim is not a style
 * choice: this card is composed once and then shown at thumbnail size over
 * somebody's chat wallpaper, and white type on an unknown photograph is
 * unreadable about half the time.
 */

function truncate(s: string, n: number): string {
  return s.length > n ? `${s.slice(0, n - 1).trimEnd()}…` : s;
}

/**
 * How long the photograph gets, and how big it may be.
 *
 * Six seconds, not the one and a half I tried first. A cold serverless
 * function doing DNS, TLS and a download is not fast, and the cost of being
 * mean here is the whole point of the feature quietly disappearing — which is
 * exactly what happened. The card is cached for a day once it is right, so
 * almost nobody waits for this.
 */
const FETCH_MS = 6000;
const MAX_BYTES = 5 * 1024 * 1024;

/**
 * What the bytes actually are, from the bytes themselves.
 *
 * Not from content-type. A header is a claim by whoever stored the file, and
 * when the claim is missing or wrong — `application/octet-stream` is the
 * usual way — trusting it means silently dropping a photograph that would
 * have decoded perfectly well. The first four bytes cannot be wrong.
 *
 * WebP is deliberately absent: Satori will not draw it, and a photograph it
 * cannot draw is better refused here than allowed to fail mid-render. Covers
 * chosen through the app are JPEG — see lib/shrink-image.ts.
 */
function sniff(b: Buffer): string | null {
  if (b.length < 8) return null;
  if (b[0] === 0xff && b[1] === 0xd8 && b[2] === 0xff) return "image/jpeg";
  if (
    b[0] === 0x89 && b[1] === 0x50 && b[2] === 0x4e && b[3] === 0x47 &&
    b[4] === 0x0d && b[5] === 0x0a && b[6] === 0x1a && b[7] === 0x0a
  ) {
    return "image/png";
  }
  if (b[0] === 0x47 && b[1] === 0x49 && b[2] === 0x46 && b[3] === 0x38) {
    return "image/gif";
  }
  return null;
}

/**
 * The photograph, as bytes we already hold.
 *
 * ── Why it is fetched here instead of passed as a URL ────────────────────
 * Because `<img src="https://…">` inside an ImageResponse is fetched while
 * the picture is being drawn, and a slow or missing file there fails the
 * whole route — after the response has begun. The card would not fall back
 * to the plain design; it would simply not arrive, and the invitation would
 * go out as a bare link.
 *
 * Fetching first makes the failure ordinary: no bytes, no photograph, and
 * the card that worked before this feature existed.
 *
 * ── Why every line of this is deliberately unclever ──────────────────────
 * This worked on a laptop and returned nothing on the real servers, twice,
 * and I could not reach those servers to watch it fail. So each thing that
 * could plausibly have been the cause is now gone rather than ruled out:
 *
 *   AbortController and a timer, not AbortSignal.timeout — the same
 *   behaviour out of older and plainer parts.
 *
 *   `cache: "no-store"`, because Next replaces global fetch with its own
 *   caching one, and a multi-megabyte binary is not what that was built for.
 *   Nothing here wants caching anyway: the finished card is what gets cached.
 *
 *   The type read from the bytes rather than the header — see sniff.
 */
async function photograph(url: string | null): Promise<string | null> {
  if (!url) return null;
  const stop = new AbortController();
  const timer = setTimeout(() => stop.abort(), FETCH_MS);
  try {
    const res = await fetch(url, { signal: stop.signal, cache: "no-store" });
    if (!res.ok) return null;

    const declared = Number(res.headers.get("content-length") ?? 0);
    if (declared > MAX_BYTES) return null;

    const buf = Buffer.from(await res.arrayBuffer());
    // Checked again: content-length is a claim, and a server that lies about
    // it would otherwise put the whole file in memory anyway.
    if (buf.byteLength === 0 || buf.byteLength > MAX_BYTES) return null;

    const type = sniff(buf);
    if (!type) return null;

    return `data:${type};base64,${buf.toString("base64")}`;
  } catch {
    // Timed out, refused, deleted, DNS — all the same answer here.
    return null;
  } finally {
    clearTimeout(timer);
  }
}

export default async function Image({ params }: { params: { slug: string } }) {
  const i = await getPublicInvitation(params.slug);

  const title = i ? truncate(i.event.title, 80) : "An invitation";
  const day = i ? longDay(i.event.at) : "";
  const hours = i ? timeRange(i.event.at, i.event.hasTime, i.event.endsAt) : "";
  // A link in the location reads as a wall of characters on a picture
  // nobody can tap, so it is shortened to the host-and-path form the page
  // shows. The card is for recognising the invitation, not for using it.
  const where = i?.event.where ? truncate(plainLinks(i.event.where), 60) : "";
  const from = i ? `From ${truncate(i.hostName, 40)}` : "";

  // Same rule as the page: no photograph above a day that was called off.
  const wanted = !!i && !i.event.cancelled && !!i.coverUrl;
  const cover = await photograph(wanted ? i!.coverUrl : null);
  /**
   * The host chose a picture and it is not on this card.
   *
   * Worth knowing, because it decides how long this is kept. A good card is
   * worth a day; this one is worth a minute, so that whatever went wrong —
   * a slow fetch, a blink from storage — is retried shortly rather than
   * frozen in front of everybody the link reaches.
   */
  const missed = wanted && !cover;

  return new ImageResponse(
    (
      <div
        style={{
          position: "relative",
          width: "100%",
          height: "100%",
          display: "flex",
          flexDirection: "column",
          justifyContent: "space-between",
          padding: "72px 80px",
          background: "#0B0E14",
          color: "#ECE8DE",
        }}
      >
        {cover && (
          // Sized in pixels, not percentages. Satori resolves `100%` on an
          // absolutely positioned child against nothing useful here, so the
          // photograph came out letterboxed with the card's own background
          // showing down two edges — which looked exactly like a broken
          // image. The canvas is a fixed 1200x630; say so.
          <img
            src={cover}
            alt=""
            width={size.width}
            height={size.height}
            style={{
              position: "absolute",
              top: 0,
              left: 0,
              width: size.width,
              height: size.height,
              objectFit: "cover",
            }}
          />
        )}
        {cover && (
          <div
            style={{
              position: "absolute",
              top: 0,
              left: 0,
              width: size.width,
              height: size.height,
              // Heavier at the foot, where the words are, and never fully
              // clear at the top — a pale sky behind pale type is the common
              // way this sort of card becomes unreadable.
              background:
                "linear-gradient(to bottom, rgba(11,14,20,0.70) 0%, rgba(11,14,20,0.78) 42%, rgba(11,14,20,0.94) 100%)",
            }}
          />
        )}

        <div
          style={{
            position: "relative",
            display: "flex",
            alignItems: "center",
            gap: 18,
          }}
        >
          <svg width="52" height="52" viewBox="0 0 120 120">
            <g transform="translate(60,60)">
              <circle cx="0" cy="0" r="52" fill="none" stroke="#ECE8DE" strokeWidth="4.5" opacity="0.4" />
              <circle cx="0" cy="0" r="34" fill="none" stroke="#ECE8DE" strokeWidth="4.5" opacity="0.72" />
              <circle cx="0" cy="0" r="9" fill="#E6A94E" />
              <circle cx="0" cy="-34" r="5.6" fill="#E6A94E" />
              <circle cx="29.4" cy="17" r="5.6" fill="#E6A94E" />
              <circle cx="-29.4" cy="17" r="5.6" fill="#E6A94E" />
            </g>
          </svg>
          <div
            style={{
              fontSize: 26,
              // On a photograph the grey disappears; on the plain card it is
              // the quiet line it has always been.
              color: cover ? "#D8D3C6" : "#8C93A3",
              letterSpacing: 4,
            }}
          >
            {from.toUpperCase()}
          </div>
        </div>

        <div
          style={{ position: "relative", display: "flex", flexDirection: "column" }}
        >
          <div
            style={{
              fontSize: 72,
              fontFamily: "serif",
              lineHeight: 1.12,
              maxWidth: 1040,
            }}
          >
            {title}
          </div>
          <div style={{ fontSize: 38, fontFamily: "serif", marginTop: 26 }}>
            {day}
          </div>
          {(hours || where) && (
            <div
              style={{
                fontSize: 26,
                color: "#E6A94E",
                letterSpacing: 5,
                textTransform: "uppercase",
                marginTop: 14,
              }}
            >
              {[hours, where].filter(Boolean).join("  ·  ")}
            </div>
          )}
        </div>

        <div
          style={{
            position: "relative",
            fontSize: 24,
            color: cover ? "#D8D3C6" : "#8C93A3",
          }}
        >
          Tap to say whether you can come · Oyun
        </div>
      </div>
    ),
    {
      ...size,
      // ── Why this header is set by hand ─────────────────────────────
      // Next's default for a metadata image is
      // `public, immutable, max-age=31536000` — keep it for a year, it will
      // never change. True of an image whose URL carries a content hash,
      // and false of ours: an invitation's card lives at one address before
      // and after the host picks a photograph. WhatsApp fetched the plain
      // card the first time the link was sent, was told to keep it for a
      // year, and did.
      //
      // So: fresh to the browser, a day on the CDN, and servable while it
      // revalidates. A card that is an hour stale is nobody's problem; a
      // card that is a year stale is the bug this replaces.
      headers: {
        // A card that came out right keeps for a day. A card that lost its
        // photograph keeps for a minute — see `missed`.
        "cache-control": missed
          ? "public, max-age=0, s-maxage=60, stale-while-revalidate=300"
          : "public, max-age=0, s-maxage=86400, stale-while-revalidate=604800",
      },
    },
  );
}
