import { ImageResponse } from "next/og";
import { getPublicInvitation } from "@/lib/invitations-db";
import { longDay, timeRange } from "@/lib/invitations";

export const runtime = "nodejs";
export const alt = "An invitation from Oyun";
export const size = { width: 1200, height: 630 };
export const contentType = "image/png";

/**
 * What the link looks like in WhatsApp.
 *
 * This decides whether anybody taps it. A bare link with no preview reads as
 * something forwarded from a stranger, and in a family group chat it gets
 * ignored. A card with the party's name and the date on it reads as an
 * invitation, which is what it is.
 *
 * It carries the title, the day and the place — everything already on the
 * public page — and nothing more. A link preview is generated by WhatsApp's
 * servers and cached who knows where, so it is the wrong place for anything
 * she would not want repeated.
 */
function truncate(s: string, n: number): string {
  return s.length > n ? `${s.slice(0, n - 1).trimEnd()}…` : s;
}

export default async function Image({ params }: { params: { slug: string } }) {
  const i = await getPublicInvitation(params.slug);

  const title = i ? truncate(i.event.title, 80) : "An invitation";
  const day = i ? longDay(i.event.at) : "";
  const hours = i ? timeRange(i.event.at, i.event.hasTime, i.event.endsAt) : "";
  const where = i?.event.where ? truncate(i.event.where, 60) : "";
  const from = i ? `From ${truncate(i.hostName, 40)}` : "";

  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          flexDirection: "column",
          justifyContent: "space-between",
          padding: "72px 80px",
          background: "#0B0E14",
          color: "#ECE8DE",
        }}
      >
        <div style={{ display: "flex", alignItems: "center", gap: 18 }}>
          <svg width="52" height="52" viewBox="0 0 120 120">
            <g transform="translate(60,60)">
              <circle cx="0" cy="0" r="52" fill="none" stroke="#ECE8DE" strokeWidth="4.5" opacity="0.4" />
              <circle cx="0" cy="0" r="34" fill="none" stroke="#ECE8DE" strokeWidth="4.5" opacity="0.72" />
              <circle cx="0" cy="0" r="9" fill="#E6A94E" />
              <circle cx="0" cy="-34" r="5.6" fill="#E6A94E" />
              <circle cx="29.4" cy="17" r="5.6" fill="#E6A94E" />
              <circle cx="-29.4" cy="17" r="5.6" fill="#E6A94E" />
            </g>
          </svg>
          <div style={{ fontSize: 26, color: "#8C93A3", letterSpacing: 4 }}>
            {from.toUpperCase()}
          </div>
        </div>

        <div style={{ display: "flex", flexDirection: "column" }}>
          <div
            style={{
              fontSize: 72,
              fontFamily: "serif",
              lineHeight: 1.12,
              maxWidth: 1040,
            }}
          >
            {title}
          </div>
          <div style={{ fontSize: 38, fontFamily: "serif", marginTop: 26 }}>
            {day}
          </div>
          {(hours || where) && (
            <div
              style={{
                fontSize: 26,
                color: "#E6A94E",
                letterSpacing: 5,
                textTransform: "uppercase",
                marginTop: 14,
              }}
            >
              {[hours, where].filter(Boolean).join("  ·  ")}
            </div>
          )}
        </div>

        <div style={{ fontSize: 24, color: "#8C93A3" }}>
          Tap to say whether you can come · Oyun
        </div>
      </div>
    ),
    { ...size },
  );
}
