import { ImageResponse } from "next/og";
import { getPublicRegistry } from "@/lib/registry-db";

export const runtime = "nodejs";
export const alt = "A registry from Oyun";
export const size = { width: 1200, height: 630 };
export const contentType = "image/png";

/**
 * What the link looks like in WhatsApp.
 *
 * This decides whether anybody taps it. A bare link with no preview reads as
 * something forwarded from a stranger and gets ignored in a family group
 * chat; a card with the family's own name on it reads as a registry, which is
 * what it is.
 *
 * It carries the title, who it is from, and how many things are on the list —
 * all of it already on the public page. No item names, no prices, no
 * photographs from any shop: a link preview is generated by somebody else's
 * servers and cached who knows where, so it is the wrong place for anything
 * she would not want repeated.
 */
function truncate(s: string, n: number): string {
  return s.length > n ? `${s.slice(0, n - 1).trimEnd()}…` : s;
}

export default async function Image({ params }: { params: { slug: string } }) {
  const r = await getPublicRegistry(params.slug, null);

  const title = r ? truncate(r.title, 70) : "A registry";
  const from = r ? `From ${truncate(r.hostName, 40)}` : "";
  const count = r?.items.length ?? 0;
  const line = r?.closed
    ? "This registry is finished"
    : count === 0
      ? "The list is being written"
      : `${count} ${count === 1 ? "thing" : "things"} on the list`;

  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          flexDirection: "column",
          justifyContent: "space-between",
          padding: "72px 80px",
          background: "#0B0E14",
          color: "#ECE8DE",
        }}
      >
        <div style={{ display: "flex", alignItems: "center", gap: 18 }}>
          <svg width="52" height="52" viewBox="0 0 120 120">
            <g transform="translate(60,60)">
              <circle cx="0" cy="0" r="52" fill="none" stroke="#ECE8DE" strokeWidth="4.5" opacity="0.4" />
              <circle cx="0" cy="0" r="34" fill="none" stroke="#ECE8DE" strokeWidth="4.5" opacity="0.72" />
              <circle cx="0" cy="0" r="9" fill="#E6A94E" />
              <circle cx="0" cy="-34" r="5.6" fill="#E6A94E" />
              <circle cx="29.4" cy="17" r="5.6" fill="#E6A94E" />
              <circle cx="-29.4" cy="17" r="5.6" fill="#E6A94E" />
            </g>
          </svg>
          <div style={{ fontSize: 26, color: "#8C93A3", letterSpacing: 4 }}>
            {from.toUpperCase()}
          </div>
        </div>

        <div style={{ display: "flex", flexDirection: "column" }}>
          <div
            style={{
              fontSize: 72,
              fontFamily: "serif",
              lineHeight: 1.12,
              maxWidth: 1040,
            }}
          >
            {title}
          </div>
          <div
            style={{
              fontSize: 26,
              color: "#E6A94E",
              letterSpacing: 5,
              textTransform: "uppercase",
              marginTop: 20,
            }}
          >
            {line}
          </div>
        </div>

        <div style={{ fontSize: 24, color: "#8C93A3" }}>
          Tap to see what is still needed · Oyun
        </div>
      </div>
    ),
    { ...size },
  );
}
